export const jobNames = [
  // Class Ⅳ
  'berserker',
  'sparta',
  'sage',
  'warlock',
  'righteousThief',
  'chaosRuler',
  'wrestler',
  'houndDog',
  'elysion',
  'apsaras',
  'chrysaor',
  'lumberjack',
  'cavalry',
  'monk',
  'robinHood',
  'relicBuster',
  'yamato',
  'shieldSworn',
  // Class Ⅴ
  'viking',
  'paladin',
  'panakeia',
  'manaDiver',
  'king',
  'onmyoji',
  'smahihi',
  // EXⅠ
  'mechanic',
  // EXⅡ
  'doctor',
  'magicWarrior',
  'kengo',
  'theGlory',
  'soldier',
  'blackCatMaster',
  'tormenter',
  'risingForce',
  'masquerade',
]

export const normalAbilities: string[] = [
  // ダメージアビリティ
  'armorBreak',
  'venom',
  'driveBurst',
  'driveBurstII',
  'driveBurstIII',
  'hardLine',
  'killStreak',
  'shining',
  'fire',
  'ice',
  'fightingSpirit',
  'arrowRain',
  'arrowRainII',
  'arrowRainIII',
  'pileLiberation',
  'resonanceSurge',
  'windNinjutsu',
  'oboro',
  'twinCircular',
  'diStream',
  // 強化アビリティ
  'rage',
  'rageII',
  'rageIII',
  'aura',
  'abandonmentForm',
  'abandonmentFormII',
  'rampage',
  'centurion',
  'focus',
  'deadlyAim',
  'elementalForce',
  'elementalForceII',
  'quick',
  'dualImpulse',
  'dualImpulseII',
  'dualImpulseIII',
  'songOfGrande',
  'rahuAshuraFormation',
  'cover',
  'spiritRaise',
  'meditation',
  'crowSparrowSilence',
  'otherMindFormation',
  'punish',
  // 弱体アビリティ
  'blind',
  'gravity',
  'miserableMist',
  'charmVoice',
  'charmVoiceII',
  'soulPilfer',
  'dispel',
  'trickStep',
  'treasureHunt',
  'treasureHuntII',
  'treasureHuntIII',
  // 回復アビリティ
  'minstrelSong',
  'clearAll',
  'revive',
  'innerKung',
  'medic',
]


/* eslint-disable @typescript-eslint/no-unused-vars, no-unused-vars */
enum JobAbilityType {
  LIMIT,
  ULTIMATE,
}
/* eslint-enable @typescript-eslint/no-unused-vars, no-unused-vars */

interface JobAbility {
  name: string;
  type: JobAbilityType;
  jobs: string[];
}

export const jobAbilities: JobAbility[] = [
  // ベルセルク系
  { name: 'job.armorBreakII', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.banaHog', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.beastFang', type: JobAbilityType.ULTIMATE, jobs: ['viking'] },
  { name: 'job.rageIV', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.rampageII', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.powerRaise', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.braveSoul', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.wulvHedin', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.vinland', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.jomsburg', type: JobAbilityType.LIMIT, jobs: ['berserker', 'viking'] },
  { name: 'job.ferocityRoar', type: JobAbilityType.ULTIMATE, jobs: ['berserker'] },
  { name: 'job.berserkerBlood', type: JobAbilityType.ULTIMATE, jobs: ['berserker'] },
  // クリュサオル系
  { name: 'job.dualArts', type: JobAbilityType.LIMIT, jobs: ['chrysaor'] },
  { name: 'job.diptych', type: JobAbilityType.LIMIT, jobs: ['chrysaor'] },
  { name: 'job.arsegal', type: JobAbilityType.LIMIT, jobs: ['chrysaor'] },
  { name: 'job.disXiphos', type: JobAbilityType.ULTIMATE, jobs: ['chrysaor'] },
  { name: 'job.astrapsyte', type: JobAbilityType.ULTIMATE, jobs: ['chrysaor'] },
  { name: 'job.amberEdge', type: JobAbilityType.ULTIMATE, jobs: ['chrysaor'] },
  { name: 'job.crossGuard', type: JobAbilityType.LIMIT, jobs: ['chrysaor'] },
  { name: 'job.chaseBlade', type: JobAbilityType.LIMIT, jobs: ['chrysaor'] },
  // ランバージャック系
  { name: 'job.greatFelling', type: JobAbilityType.LIMIT, jobs: ['lumberjack'] },
  { name: 'job.woodSplitting', type: JobAbilityType.ULTIMATE, jobs: ['lumberjack'] },
  { name: 'job.peacefulSunlight', type: JobAbilityType.LIMIT, jobs: ['lumberjack'] },
  { name: 'job.fallenLeavesBurning', type: JobAbilityType.LIMIT, jobs: ['lumberjack'] },
  { name: 'job.greenMelody', type: JobAbilityType.ULTIMATE, jobs: ['lumberjack'] },
  { name: 'job.fragrantBreezeAndChirping', type: JobAbilityType.ULTIMATE, jobs: ['lumberjack'] },
  // ヤマト系
  { name: 'job.kenmonItto', type: JobAbilityType.LIMIT, jobs: ['yamato'] },
  { name: 'job.sanryuKairetsu', type: JobAbilityType.LIMIT, jobs: ['yamato'] },
  { name: 'job.amentotsukaSword', type: JobAbilityType.ULTIMATE, jobs: ['yamato'] },
  { name: 'job.hakuhyoRanryu', type: JobAbilityType.LIMIT, jobs: ['yamato'] },
  { name: 'job.orochiNoIbuki', type: JobAbilityType.ULTIMATE, jobs: ['yamato'] },
  { name: 'job.kiyoharaiNoKagura', type: JobAbilityType.ULTIMATE, jobs: ['yamato'] },
  // ウォーロック系
  { name: 'job.bounce', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.replicationCast', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.wildMagica', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.demonsFlare', type: JobAbilityType.ULTIMATE, jobs: ['manaDiver'] },
  { name: 'job.choke', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.chaser', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.secretTriad', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.overTrance', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.magicBarrier', type: JobAbilityType.ULTIMATE, jobs: ['manaDiver'] },
  { name: 'job.magicSealRelease', type: JobAbilityType.ULTIMATE, jobs: ['manaDiver'] },
  { name: 'job.blackHaze', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  { name: 'job.etherFlap', type: JobAbilityType.LIMIT, jobs: ['warlock', 'manaDiver'] },
  // カオスルーダー系
  { name: 'job.bleakDisorder', type: JobAbilityType.ULTIMATE, jobs: ['chaosRuler'] },
  { name: 'job.shikigamiKo', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.uplift', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.absorb', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.tenchiKaibyaku', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.quickDown', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.unpredict', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.flameOfChaos', type: JobAbilityType.ULTIMATE, jobs: ['chaosRuler'] },
  { name: 'job.enormity', type: JobAbilityType.ULTIMATE, jobs: ['chaosRuler'] },
  { name: 'job.curseSynergy', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  { name: 'job.chaos', type: JobAbilityType.LIMIT, jobs: ['chaosRuler', 'onmyoji'] },
  // 剣豪系
  { name: 'job.otakaGaeshi', type: JobAbilityType.LIMIT, jobs: ['kengo'] },
  { name: 'job.hamaNoGen', type: JobAbilityType.ULTIMATE, jobs: ['kengo'] },
  { name: 'job.hiikenGokuIssen', type: JobAbilityType.ULTIMATE, jobs: ['kengo'] },
  { name: 'job.unsanMusho', type: JobAbilityType.LIMIT, jobs: ['kengo'] },
  { name: 'job.mumyoGiri', type: JobAbilityType.LIMIT, jobs: ['kengo'] },
  { name: 'job.retsuToIssen', type: JobAbilityType.LIMIT, jobs: ['kengo'] },
  { name: 'job.tatsugan', type: JobAbilityType.ULTIMATE, jobs: ['kengo'] },
  // ライジングフォース系
  { name: 'job.unleashTheFury', type: JobAbilityType.LIMIT, jobs: ['risingForce'] },
  { name: 'job.pickingHarmonics', type: JobAbilityType.ULTIMATE, jobs: ['risingForce'] },
  { name: 'job.rhythmResonance', type: JobAbilityType.LIMIT, jobs: ['risingForce'] },
  { name: 'job.moshBit', type: JobAbilityType.LIMIT, jobs: ['risingForce'] },
  { name: 'job.jetToJet', type: JobAbilityType.LIMIT, jobs: ['risingForce'] },
  { name: 'job.enthusiasm', type: JobAbilityType.ULTIMATE, jobs: ['risingForce'] },
  { name: 'job.everlastingTies', type: JobAbilityType.ULTIMATE, jobs: ['risingForce'] },
]