export const jobNames = [
  // Class Ⅳ
  'ベルセルク',
  'スパルタ',
  'セージ',
  'ウォーロック',
  '義賊',
  'カオスルーダー',
  'レスラー',
  'ハウンドドッグ',
  'エリュシオン',
  'アプサラス',
  'クリュサオル',
  'ランバージャック',
  'キャバルリー',
  'モンク',
  'ロビンフッド',
  'レリックバスター',
  '大和',
  'シールドスウォーン',
  // Class Ⅴ
  'ヴァイキング',
  'パラディン',
  'パナケイア',
  'マナダイバー',
  'キング',
  '陰陽師',
  'スマヒヒト',
  // EXⅠ
  'メカニック',
  // EXⅡ
  'ドクター',
  '魔法戦士',
  '剣豪',
  'ザ・グローリー',
  'ソルジャー',
  '黒猫道師',
  'トーメンター',
  'ライジングフォース',
  'マスカレード',
]

export const normalAbilities: string[] = [
  // ダメージアビリティ
  'アーマーブレイク',
  'ヴェノム',
  'ドライブバースト',
  'ドライブバーストⅡ',
  'ドライブバーストⅢ',
  'ハードライン',
  'キルストリーク',
  'シャイニング',
  'ファイア',
  'アイス',
  '闘気',
  'アローレイン',
  'アローレインⅡ',
  'アローレインⅢ',
  'パイルリベレーション',
  'レゾナンスサージ',
  '風魔手裏剣',
  '朧',
  'ツインサーキュラー',
  'ディストリーム',
  // 強化アビリティ
  'レイジ',
  'レイジⅡ',
  'レイジⅢ',
  'オーラ',
  '捨身の型',
  '捨身の型Ⅱ',
  'ランページ',
  'センチュリオン',
  'フォーカス',
  'デッドリーエイム',
  'エレメンタルフォース',
  'エレメンタルフォースⅡ',
  'クイック',
  'デュアルインパルス',
  'デュアルインパルスⅡ',
  'デュアルインパルスⅢ',
  'ソング・オブ・グランデ',
  '羅喉阿修羅陣',
  'かばう',
  '士気向上',
  '瞑想',
  '鴉雀無声',
  '他心陣',
  'パニッシュ',
  // 弱体アビリティ
  'ブラインド',
  'グラビティ',
  'ミゼラブルミスト',
  'チャームボイス',
  'チャームボイスⅡ',
  'ソウルピルファー',
  'ディスペル',
  'トリックステップ',
  'トレジャーハント',
  'トレジャーハントⅡ',
  'トレジャーハントⅢ',
  // 回復アビリティ
  'ミンストレルソング',
  'クリアオール',
  'リヴァイブ',
  '内功',
  'メディク',
]


/* eslint-disable @typescript-eslint/no-unused-vars, no-unused-vars */
enum JobAbilityType {
  LIMIT,
  ULTIMATE,
}
/* eslint-enable @typescript-eslint/no-unused-vars, no-unused-vars */

interface JobAbility {
  name: string;
  type: JobAbilityType;
  jobs: string[];
}

export const jobAbilities: JobAbility[] = [
  // ベルセルク系
  { name: 'アーマーブレイクⅡ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'バナホッグ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ビーストファング', type: JobAbilityType.ULTIMATE, jobs: ['ヴァイキング'] },
  { name: 'レイジⅣ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ランページⅡ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'パワーレイズ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ブレイブソウル', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ウールヴヘジン', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ヴィンランド', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'ヨムスボルグ', type: JobAbilityType.LIMIT, jobs: ['ベルセルク', 'ヴァイキング'] },
  { name: 'フェロシティロアー', type: JobAbilityType.ULTIMATE, jobs: ['ベルセルク'] },
  { name: '狂戦の血', type: JobAbilityType.ULTIMATE, jobs: ['ベルセルク'] },
  // クリュサオル系
  { name: 'デュアルアーツ', type: JobAbilityType.LIMIT, jobs: ['クリュサオル'] },
  { name: 'ディプティク', type: JobAbilityType.LIMIT, jobs: ['クリュサオル'] },
  { name: 'アーセガル', type: JobAbilityType.LIMIT, jobs: ['クリュサオル'] },
  { name: 'ディス・クシフォス', type: JobAbilityType.ULTIMATE, jobs: ['クリュサオル'] },
  { name: 'アストラプシテ', type: JobAbilityType.ULTIMATE, jobs: ['クリュサオル'] },
  { name: 'アンバーエッジ', type: JobAbilityType.ULTIMATE, jobs: ['クリュサオル'] },
  { name: 'クロスガード', type: JobAbilityType.LIMIT, jobs: ['クリュサオル'] },
  { name: 'チェイスブレード', type: JobAbilityType.LIMIT, jobs: ['クリュサオル'] },
  // ランバージャック系
  { name: '大伐断', type: JobAbilityType.LIMIT, jobs: ['ランバージャック'] },
  { name: '薪割り', type: JobAbilityType.ULTIMATE, jobs: ['ランバージャック'] },
  { name: '安らぎの木もれ日', type: JobAbilityType.LIMIT, jobs: ['ランバージャック'] },
  { name: '落ち葉焚き', type: JobAbilityType.LIMIT, jobs: ['ランバージャック'] },
  { name: '緑の旋律', type: JobAbilityType.ULTIMATE, jobs: ['ランバージャック'] },
  { name: '薫風とさえずり', type: JobAbilityType.ULTIMATE, jobs: ['ランバージャック'] },
  // ヤマト系
  { name: '見聞一刀', type: JobAbilityType.LIMIT, jobs: ['ヤマト'] },
  { name: '山隆海裂', type: JobAbilityType.LIMIT, jobs: ['ヤマト'] },
  { name: '天十握剣', type: JobAbilityType.ULTIMATE, jobs: ['ヤマト'] },
  { name: '白雹乱流', type: JobAbilityType.LIMIT, jobs: ['ヤマト'] },
  { name: '大蛇之息吹', type: JobAbilityType.ULTIMATE, jobs: ['ヤマト'] },
  { name: '清祓之神楽', type: JobAbilityType.ULTIMATE, jobs: ['ヤマト'] },
  // ウォーロック系
  { name: 'バウンス', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'レプリケーションキャスト', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'ワイルドマギカ', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'デモンズフレア', type: JobAbilityType.ULTIMATE, jobs: ['マナダイバー'] },
  { name: 'チョーク', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'チェイサー', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'シークレットトライアド', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'オーバートランス', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: '魔術結界', type: JobAbilityType.ULTIMATE, jobs: ['マナダイバー'] },
  { name: '魔紋解放', type: JobAbilityType.ULTIMATE, jobs: ['マナダイバー'] },
  { name: 'ブラックヘイズ', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  { name: 'エーテルフラップ', type: JobAbilityType.LIMIT, jobs: ['ウォーロック', 'マナダイバー'] },
  // カオスルーダー系
  { name: 'ブリークディスオーダー', type: JobAbilityType.ULTIMATE, jobs: ['カオスルーダー'] },
  { name: '式神・蛟', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'アップリフト', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'アブソーブ', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: '天地開闢', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'クイックダウン', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'アンプレディクト', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'フレイム・オブ・カオス', type: JobAbilityType.ULTIMATE, jobs: ['カオスルーダー'] },
  { name: 'イノーミティ', type: JobAbilityType.ULTIMATE, jobs: ['カオスルーダー'] },
  { name: '呪々相乗', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  { name: 'カオス', type: JobAbilityType.LIMIT, jobs: ['カオスルーダー', '陰陽師'] },
  // 剣豪系
  { name: '大鷲返し', type: JobAbilityType.LIMIT, jobs: ['剣豪'] },
  { name: '破魔ノ弦', type: JobAbilityType.ULTIMATE, jobs: ['剣豪'] },
  { name: '秘剣・極一閃', type: JobAbilityType.ULTIMATE, jobs: ['剣豪'] },
  { name: '雲散霧消', type: JobAbilityType.LIMIT, jobs: ['剣豪'] },
  { name: '無明斬', type: JobAbilityType.LIMIT, jobs: ['剣豪'] },
  { name: '列刀一閃', type: JobAbilityType.LIMIT, jobs: ['剣豪'] },
  { name: '達眼', type: JobAbilityType.ULTIMATE, jobs: ['剣豪'] },
  // ライジングフォース系
  { name: 'アンリーシュザフューリー', type: JobAbilityType.LIMIT, jobs: ['ライジングフォース'] },
  { name: 'ピッキング・ハーモニクス', type: JobAbilityType.ULTIMATE, jobs: ['ライジングフォース'] },
  { name: '律動共振', type: JobAbilityType.LIMIT, jobs: ['ライジングフォース'] },
  { name: 'モッシュビット', type: JobAbilityType.LIMIT, jobs: ['ライジングフォース'] },
  { name: 'ジェット・トゥ・ジェット', type: JobAbilityType.LIMIT, jobs: ['ライジングフォース'] },
  { name: 'インスージアズム', type: JobAbilityType.ULTIMATE, jobs: ['ライジングフォース'] },
  { name: 'エヴァーラスティングタイズ', type: JobAbilityType.ULTIMATE, jobs: ['ライジングフォース'] },
]